<?php
/**
 * Created by PhpStorm.
 * User: walkskyer
 * Date: 2016/6/13
 * Time: 22:14
 */

namespace app\components\db;


class ActiveRecord extends \yii\db\ActiveRecord{

    public function beforeSave($insert) {
        if($this->hasAttribute('modified')){
            $this->modified = time();
        }
        if($this->hasAttribute('dateline') && $this->isNewRecord){
            $this->dateline = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}